### ISSUE TITLE
Can't install on OS X 10.11

### ISSUE THREAD

**Issue by kaendfinger** [PressLabs/gitfs#196]
I'm having issues installing gitfs on OS X 10.11

Logs: https://gist.github.com/kaendfinger/4275d68ac2bf1817492b

**Comment by dragostis** [comment]
Thank you for reporting the issue. Unfortunately, OS X 10.11 El Capitan is not yet supported since it's still in development and the underlying software that gitfs uses is not yet compatible.

We'll make sure gitfs works well with El Capitan once it's fully launched, since new betas of the OS might break compatibility again and again.

**Comment by kaendfinger** [comment]
@dragostis Thanks :)

**Comment by oschrenk** [comment]
Seems a lot better nowadays.[OSXFuse 2.8.2](https://osxfuse.github.io/2015/10/25/OSXFUSE-2.8.2.html) seems to be ready for El Capitan and installs fine.

But I do get some hickups

```
gitfs https://github.com/PressLabs/gitfs.git ~/Downloads/gitfs                         
Traceback (most recent call last):
  File "/usr/local/Cellar/gitfs/0.3.3/libexec/bin/gitfs", line 9, in <module>
    load_entry_point('gitfs==0.3.3', 'console_scripts', 'gitfs')()
  File "/usr/local/Cellar/gitfs/0.3.3/libexec/lib/python2.7/site-packages/gitfs/__init__.py", line 20, in mount
    start_fuse()
  File "/usr/local/Cellar/gitfs/0.3.3/libexec/lib/python2.7/site-packages/gitfs/mounter.py", line 98, in start_fuse
    args = parse_args(parser)
  File "/usr/local/Cellar/gitfs/0.3.3/libexec/lib/python2.7/site-packages/gitfs/mounter.py", line 38, in parse_args
    return Args(parser)
  File "/usr/local/Cellar/gitfs/0.3.3/libexec/lib/python2.7/site-packages/gitfs/utils/args.py", line 61, in __init__
    self.config = self.build_config(parser.parse_args())
  File "/usr/local/Cellar/gitfs/0.3.3/libexec/lib/python2.7/site-packages/gitfs/utils/args.py", line 70, in build_config
    return self.check_args(self.set_defaults(args))
  File "/usr/local/Cellar/gitfs/0.3.3/libexec/lib/python2.7/site-packages/gitfs/utils/args.py", line 133, in set_defaults
    value = value(args)
  File "/usr/local/Cellar/gitfs/0.3.3/libexec/lib/python2.7/site-packages/gitfs/utils/args.py", line 164, in get_repo_path
    return tempfile.mkdtemp(dir="/var/lib/gitfs")
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tempfile.py", line 333, in mkdtemp
    _os.mkdir(file, 0700)
OSError: [Errno 2] No such file or directory: '/var/lib/gitfs/tmpR0ah86'
```

True enough. `/var/lib/gitfs/` doesn't exist. Let's create it (disclaimer: I have multiple users in a group called `Local` ).

```
sudo mkdir /var/lib/gitfs
sudo chown -R admin:Local /var/lib/gitfs/
sudo chmod -R +a "group:Local allow delete,readattr,writeattr,readextattr,writeextattr,list,search,add_file,add_subdirectory,delete_child,file_inherit,directory_inherit" /var/lib/gitfs
```

Create mountpoint

```
mkdir ~/Downloads/gitfs 
```

```
gitfs https://github.com/PressLabs/gitfs.git ~/Downloads/gitfs
mount_osxfusefs: failed to mount /Users/oliver/Downloads/grid@/dev/osxfuse0: Operation not permitted
```

As an admin user it actually works though, at least for a few seconds

```
su admin
mkdir ~/Downloads/gitfs
gitfs https://github.com/PressLabs/gitfs.git ~/Downloads/gitfs
cd ~/Downloads/gitfs
ls
current history

# wait a few seconds

ls -la
ls: .: Device not configured
```

**Comment by talios** [comment]
Since El Capitan is now released - has anyone looked at this?  Was trying to install gitfs yesterday and hit the issue.

**Comment by mhulse** [comment]
:+1:

**Comment by mhulse** [comment]
:+1: … At a very minimum, it would have been nice to be warned on this page:

https://www.presslabs.com/gitfs/docs/usage/

Looking forward to using this code once El Capitan is supported! :octocat:

**Comment by paulstelian97** [comment]
The "wontfix" label should be removed and this issue investigated again. El Capitan might be a rather significant fraction of the user base.

**Comment by vtemian** [comment]
@paulstelian97 you are right, changing it to must.

**Comment by calind** [comment]
Hey @dragostis, do you have any updates?

**Comment by dragostis** [comment]
@calind I'm travelling these days. I'll take a look this weekend or next week.

**Comment by dragostis** [comment]
I'm currently getting an error from `clang` when trying to install `pygit2`. What are the right dependencies?

Current dependencies can be found [here](https://github.com/Homebrew/homebrew-fuse/blob/master/Formula/gitfs.rb).

**Comment by milero** [comment]
Maybe this is what you need? https://github.com/PressLabs/gitfs/blob/master/requirements.txt

**Comment by vtemian** [comment]
This may be fixed in https://github.com/Homebrew/homebrew-fuse/commit/cc5f2386a073300a9e750ad0ce7b5d604ee0dd2f. We need to check.

**Comment by Sidnicious** [comment]
No: `/var/lib` isn't writable by normal users. If you're going for a temporary directory (which I'm not sure if you are), then a plain `tempfile.mkdtemp('gitfs')` will do the right thing.

FWIW, I had to make the below changes to the formula to get it to build and run at all on 10.11 with Xcode 8, but I still ran into this issue. I'd be happy to PR the formula change, but it's pretty small.

```.diff
diff --git a/Formula/gitfs.rb b/Formula/gitfs.rb
index d0bd2bf..206aa2b 100644
--- a/Formula/gitfs.rb
+++ b/Formula/gitfs.rb
@@ -38,7 +38,16 @@ class Gitfs < Formula
     sha256 "105f8d68616f8248e24bf0e9372ef04d3cc10104f1980f54d57b2ce73a5ad56a"
   end
 
+  resource "pycparser" do
+    url "https://files.pythonhosted.org/packages/6d/31/666614af3db0acf377876d48688c5d334b6e493b96d21aa7d332169bee50/pycparser-2.14.tar.gz"
+    sha256 "7959b4a74abdc27b312fed1c21e6caf9309ce0b29ea86b591fd2e99ecdf27f73"
+  end
+
   def install
+    unless MacOS::CLT.installed?
+      ENV.append "CFLAGS", "-I#{MacOS.sdk_path}/usr/include/ffi" # libffi
+    end
+
     virtualenv_install_with_resources
   end
```

**Comment by t-ionut** [comment]
@Sidnicious thanks for this, I've tested your modified gitfs recipe and it works on an iMac running 10.10.5 on which gitfs also didn't install correctly.

Regarding your second issue, you can change the path on which your repository is cloned using `gitfs -o repo_path=/tmp/some_repo` to avoid permission issues.

For further notice we should give all configurable options on `gitfs -h` (https://github.com/PressLabs/gitfs/issues/252)

I'll make a PR with this recipe

**Comment by t-ionut** [comment]
Waiting for https://github.com/Homebrew/homebrew-fuse/pull/75 to be reviewed, closing this issue.

**Comment by Sidnicious** [comment]
Whoo, thanks! For what it's worth, a better default path on OS X might be a good complement to improved docs, but it's good to know about this workaround.
