### ISSUE TITLE
Port to python3 [$20]

### ISSUE THREAD

**Issue by vtemian** [PressLabs/gitfs#199]
Gitfs was written using only Python 2 code, but now, as the things in Python 3 evolves and are very stable, we need to port our Python 2 code to Python 3 compatible code.

**Comment by cdvv7788** [comment]
This will probably rise some issues after the update for things not covered in the tests. I will give it a go this week.

**Comment by goranpavlovic** [comment]
I will work on this in this week. Can you have any suggestions for me? Thanks

**Comment by vtemian** [comment]
Hi guys,

@cdvv7788 yep, 3.4 sounds great.
@goranpavlovic you can find some tools and articles online:
  * https://docs.python.org/2/howto/pyporting.html
  * pylint has a special mode `--py3k` in which it will show you some compatibility problems

**Comment by goranpavlovic** [comment]
I have solved some of problems. 
1. Compatiblity issue with python basestiring function, python3 does not have defined this function.
2. Compatibility issue with timestamp.
3. Compatibility issue with iteritems function.
4. Issues with different way to use octal numbers in python2 and python3 which you use for permissions.
5. Different way for using urllib functionality.
6. Issue with queue class in python versions 2 and 3.

After that changes
I have installed application normally to python3 virtual environment.
Also application is successfully started. 

But i just have one problem for now , when i go to directory which is mounted using gitfs
and on index route try to get list of files with command ls or ls -als
i get this error: 
ls: reading directory .: Function not implemented
total 0

But in index view and in python2.7 environment i see that output should be ['.', '..', 'current', 'history']

Function readdir is not called.

I assume that i have compatibility issue with some interfaces or classes such as
some method name was changed or something like that.

I will continue work on this problem.

Thanks

**Comment by justuswilhelm** [comment]
Hi, I've created a solution with #212, it includes working tests both on drone and vagrant.

**Comment by justuswilhelm** [comment]
@vtemian Can the issue be closed?

**Comment by vtemian** [comment]
Yep
