### ISSUE TITLE
Bugs bounty [$10]

### ISSUE THREAD

**Issue by vtemian** [PressLabs/gitfs#200]
We want to make `gitfs` as stable as possible, so we are in search for bugs.
We'll add a bounty on bountysource.com for each discovered bug.
##

**Comment by Prashant-Surya** [comment]
@vtemian so solving this issue is by adding it in bountysource?

**Comment by jack17529** [comment]
So putting 10$ solves this bug??

**Comment by vtemian** [comment]
I think that for now we can close this issue.
