### ISSUE TITLE
brew install: Error: undefined method `desc' for Formulary::Formulae::Gitfs:Class

### ISSUE THREAD

**Issue by kenorb** [PressLabs/gitfs#204]
On OS X I've installed initially as:

    brew install gitfs

and it worked, but then I've seen the instructions [here](https://www.presslabs.com/gitfs/docs/usage/) to install it via:

    brew install homebrew/fuse/gitfs

but this method doesn't work, as it fails with the error:

	Error: undefined method `desc' for Formulary::Formulae::Gitfs:Class
	Please report this bug:
	    https://git.io/brew-troubleshooting
	/usr/local/Library/Taps/homebrew/homebrew-fuse/Formula/gitfs.rb:2:in `<class:Gitfs>'
	/usr/local/Library/Taps/homebrew/homebrew-fuse/Formula/gitfs.rb:1:in `load_file'
	/usr/local/Library/Homebrew/formulary.rb:92:in `module_eval'
	/usr/local/Library/Homebrew/formulary.rb:92:in `load_file'

What's the difference between `gitfs` and `homebrew/fuse/gitfs` and which one I should use?
Is there anything to fix (instructions on the site or the formula it-self?

--
UPDATE: After I've updated brew (`brew update`), now I've these errors:

	$ brew install homebrew/fuse/gitfs
	==> Installing gitfs from homebrew/homebrew-fuse
	==> Downloading https://github.com/PressLabs/gitfs/archive/0.2.5.tar.gz
	Already downloaded: /Library/Caches/Homebrew/gitfs-0.2.5.tar.gz
	==> Downloading https://pypi.python.org/packages/source/f/fusepy/fusepy-2.0.2.tar.gz
	Already downloaded: /Library/Caches/Homebrew/gitfs--fusepy-2.0.2.tar.gz
	==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/gitfs/0.2.5/libexec/vendor --single-version-externally-managed --record=installed.txt
	==> Downloading https://pypi.python.org/packages/source/p/pygit2/pygit2-0.22.0.tar.gz
	Already downloaded: /Library/Caches/Homebrew/gitfs--pygit2-0.22.0.tar.gz
	==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/gitfs/0.2.5/libexec/vendor --single-version-externally-managed --record=installed.txt
	  File "/private/tmp/gitfs--pygit220150906-84496-1rvzuni/pygit2-0.22.0/cffi-1.2.1-py2.7-macosx-10.9-intel.egg/cffi/ffiplatform.py", line 38, in compile
	    outputfilename = _build(tmpdir, ext)
	  File "/private/tmp/gitfs--pygit220150906-84496-1rvzuni/pygit2-0.22.0/cffi-1.2.1-py2.7-macosx-10.9-intel.egg/cffi/ffiplatform.py", line 65, in _build
	    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
	cffi.ffiplatform.VerificationError: CompileError: command 'clang' failed with exit status 1

**Comment by pdobrescu** [comment]
Thanks for reporting this. 
What is the OS X version that you're using? We'll investigate what is going on.

**Comment by kenorb** [comment]
I'm using 10.9.5 (Maverick).

I've re-checked again by:

    brew reinstall gitfs --force
    brew reinstall homebrew/fuse/gitfs --force

And I don't have this error anymore, so I think it's fixed right now for some reason.

Thanks for your help. I'll come back when I've again.
