### ISSUE TITLE
Misaligned code bug

### ISSUE THREAD

**Issue by neosilky** [PressLabs/gitfs#208]
Hi guys,

I was just checking out the source code, coming from BountySource. I noticed on [lines 446 - 462](https://github.com/PressLabs/gitfs/blob/master/gitfs/repository.py#L454), the code is not indented. They are referencing `first_commit` and `second_commit` which are only defined within the loop.

Let me know if this is correct and I'll fire away a PR.

~ Daniel

**Comment by vtemian** [comment]
Hi,

Awesome find!
Even though this code is valid and correct in Python 2&3, it would be nice that those variables to be defined before the loop or to find a more readable solution.
I would be happy to see a PR for this issue :+1:

**Comment by neosilky** [comment]
Ah okay! - After investigating I found out that Python does not follow the same scoping scheme I am used to in other languages. Still, I will send a pull request to make it slightly shorter and fix this issue from appearing in my linter.

**Comment by vtemian** [comment]
@neosilky, do you want to submit a new pull request for this issue or can I close it?
