### ISSUE TITLE
Binaries for Ubuntu 15.10 (Wily Werewolf)

### ISSUE THREAD

**Issue by arjamizo** [presslabs/gitfs#213]
Could you provide binaries on https://launchpad.net/~presslabs/+archive/ubuntu/gitfs so one might try using `gitfs` on the newest Ubuntu? Thanks in advance!
##

**Comment by vtemian** [comment]
Hi @arjamizo, 

For now we don't have any binaries for Ubuntu 15+, but we hope that we'll build a new release as soon as possible.

You can build the binaries using the debian branch (https://github.com/PressLabs/gitfs/tree/debian).

**Comment by vtemian** [comment]
We'll no longer support ubuntu versions lower than 18.04.
