### ISSUE TITLE
SyncWorker fails silently

### ISSUE THREAD

**Issue by vtemian** [PressLabs/gitfs#214]
Sometimes, under suspect circumstances, SyncWorker will fail and no synchronization will be done.

**Comment by krodyrobi** [comment]
@vtemian are there any logs that would suggest it failing or a starting point for the investigation?

**Comment by calind** [comment]
First step would be to bump the debug level to DEBUG in order to catch a stacktrace.

**Comment by krodyrobi** [comment]
I've enabled the debug flag for zmescience / dev-zmescience / zmemusic.

Log paths /var/log/gitfs-debug-<instance> on sftp.presslabs.net
