### ISSUE TITLE
Revisit install dependencies

### ISSUE THREAD

**Issue by krodyrobi** [PressLabs/gitfs#215]

**Comment by vtemian** [comment]
Can you add more details?

**Comment by krodyrobi** [comment]
the default pip install does not work completely: libgit2 does not work with apt-get needs built to compatible version + pygit proper versions (not backwards compatible) python-cffi vs cffi libffi libffi-dev etc all of which are needed but not easily installed (a make file would be nice)

**Comment by calind** [comment]
@krodyrobi will be fixed in 0.3.4 release.
