### ISSUE TITLE
Make test does fails almost every test with the current build?

### ISSUE THREAD

**Issue by krodyrobi** [PressLabs/gitfs#217]
Doing all that is in Contrib.md results in read / write push failures during the tests.
To be investigated if something broke.

**Comment by calind** [comment]
@krodyrobi please elaborate

**Comment by krodyrobi** [comment]
It maybe something from my part as if i run them with sudo in the virtual env they work as expected..
I'd close this issue as 2 people after me haven't had this issue :D
