### ISSUE TITLE
libgit2 not installable

### ISSUE THREAD

**Issue by kamilszewczyk** [presslabs/gitfs#247]
Hi,
I'm trying to install gitfs on Linux Mint using PPA provided, however after apt-get install I'm getting "gitfs : Depends: libgit2 but it is not installable!"
Can't find the package libgit2 to install. Can anyone help me how to solve this problem?
Thanks

**Comment by vtemian** [comment]
Hi @kamilszewczyk,

Thanks for the issue. I've looked into it and updated the packages.
Can you do an update and re-install?

```
sudo apt-get update
sudo apt-get install gitfs
```
