### ISSUE TITLE
Installing on ubuntu 16.04

### ISSUE THREAD

**Issue by wmantly** [presslabs/gitfs#268]
Has any one ever got this to install on ubuntu 16.04? The install does not work from source or from pip.

**Comment by vtemian** [comment]
Hi @wmantly,

For now we don't support Ubuntu 16.04, but we have this issue in our road-map.
The pip installation is not supported anymore, only packages via ppa (https://launchpad.net/~presslabs/+archive/ubuntu/gitfs).

**Comment by wmantly** [comment]
I was able to get it to install using this repo by installing python3.4 and changing the version of pygit2 to 24. After running, it gave me permission issue about writing to `/var/lib/gitfs/*`, after changing the permission of that folder to 777 it runs with out error, but does nothing. Nothing appears in the specified mount dir or in the `/var/lib/gitfs/*` folder and there are zero error messages. 
I was using this command
```bash
gitfs https://<authToken>@github.com/wmantly/jqspa.git ~/gitfs
```

Running on ubuntu 14.04 worked somewhat better. I had the same issue with `/var/lib/gitfs/*` but the files would mount but my changes would were not pushed to github.

I look forward to support for ubuntu 16.04!

**Comment by vtemian** [comment]
Sadly, we dropped support for ubuntu 16.04, but you can install it via pip, you'll just need libgit2 == 0.28.X, since pygit2 requires it.
Sadly, there are no offical builds for it, so you'll need to build it yourself.
Besides that, it should be all good.

Sorry for the delay.
