### ISSUE TITLE
pygit2 version needs to be bumped

### ISSUE THREAD

**Issue by ilovezfs** [presslabs/gitfs#273]
pygit2 0.26.0 adds support for libgit2 0.26.0, so the version in requirements.txt should be bumped so that gitfs doesn't conflict with the latest libgit2.

Cf. https://github.com/Homebrew/homebrew-core/pull/14731

As a side note, fusepy 2.0.4 is also available now.

**Comment by omgold** [comment]
I second this. On Arch I'm running it with:

fusepy==2.0.4
pygit2==0.26.0
raven==6.1.0

And it works well enough (after changing the requirements file, of course). Obviously pinning the versions this restrictive is not needed.

**Comment by ilovezfs** [comment]
@vtemian gentle ping on this.

**Comment by vtemian** [comment]
We just released 0.5.1 with pygit 0.28.2 and fresh debs for ubuntu 18.04, 19.04 and 19.10.

Sorry for the delay.
