### ISSUE TITLE
Ubuntu 19.04

### ISSUE THREAD

**Issue by sixtyfive** [presslabs/gitfs#306]
More of a question than an issue: are there plans to at some point have packages for Ubuntu 19.04 in the PPA (and 18.04.3 for that matter)? https://www.presslabs.com/code/gitfs/how-to-use-gitfs/#installing informs us about "fully supporting" 12.04 and 14.04 "now", which is not too confidence-inspiring...

**Comment by vtemian** [comment]
@sixtyfive we just released the 0.5.1 version with packages for ubuntu 18.04, 19.04 and 19.10.
Can you try them out and see if they work as expected?

**Comment by sixtyfive** [comment]
Sorry, @vtemian, my use case has gone away meanwhile.
