### ISSUE TITLE
What is the state of this project?

### ISSUE THREAD

**Issue by maltris** [presslabs/gitfs#308]
Pull requests don't seem to get merged, Issues don't seem to get answered, no packages for any up-to-date distros are being packaged.

Is this project abandoned?

**Comment by vtemian** [comment]
Hello @maltris!

For now, the project is not anymore maintained, as you pointed out. 
We'll try to migrate to the new pygit2 versions and publish packages for distros as well.

Please feel free to contribute as well.

**Comment by vtemian** [comment]
We've managed to update the dependencies and push new packages for Ubuntu 18.04, 19.04 and 19.10.

We're working on building packages for macOS, CenOS and Fedora.
